
$(function(){if(typeof HJPassport!=='undefined'){var subName='//pass';if(window.location.host!='dict.hjenglish.com'&&window.location.host!='yz.dict.hjenglish.com'){subName='//pass2';}
HJPassport.init({source:'newd',API_SLD:subName});$('#loginBtn').bind('click',function(){HJPassport.show('login');});$('#registerBtn').bind('click',function(){HJPassport.show('register');});}
window.hjquicklogin.init();});window.hjquicklogin={init:function(){var me=this;$(".fastLogin").click(function(){me.login();});$(".fastRegister").click(function(){me.register();});},doLogin:function(){HJPassport.show('login');},doRegister:function(){HJPassport.show('register');}};
if(typeof hjd_hasComment=="undefined"){hjd_hasComment="1";}
var OldWord="";var JustInputForTimer="";var lastResult=[];var lastComments=[];var InputTimer=0;var sugSelectIndex=-1;var hasResult=false;var subEnabled=false;var selectOpen=false;var searchWord=true;var tmpWord="";function DetectInput(){var tword=$("#w").val();if(searchWord)
{OnWordChange();}}
function ShiftSelect(aIndex){if(hasResult){if(aIndex>lastResult.length-1){aIndex=0;}else if(aIndex<0){aIndex=lastResult.length;}
var aIndex2=Math.max(Math.min(aIndex,lastResult.length-1),0);if(sugSelectIndex!=aIndex2){$("#suglist > div").eq(sugSelectIndex).removeClass("itemOver").addClass("itemNormal");sugSelectIndex=aIndex2;var aWord=$("#suglist > div").eq(aIndex2).removeClass("itemNormal").addClass("itemOver").find("span:first").text();document.getElementById("suglist").scrollTop=18*(sugSelectIndex-3);SetWinput(aWord);}
$("#suglist_panel").css("display","block");}else{}}
function SetWinput(aWord){aWord=aWord.replace(/【\S*】/igm,"");aWord=aWord.replace(/【\S*.../igm,"");$("#w").val(aWord);OldWord=JustInputForTimer=aWord;}
function SugLoaded(data){if(data.length>0){try{data=eval(data);lastResult=data[1];if(data.length==3){lastComments=eval(data)[2];}else{lastComments=[];}
$("#suglist").html("");hasResult=true;if(lastResult.length>10){$("#suglist").css("height","250px");}else{$("#suglist").css("height","auto");}
sugSelectIndex=-1;var reg=new RegExp("("+OldWord+")","igm");if(lastComments.length!=0){var tHtml="";$.each(lastResult,function(aIndex){var dbWord=lastResult[aIndex];var tmp="<b>"+dbWord.substr(0,OldWord.length)+"</b>"+dbWord.substr(OldWord.length);tHtml+="<div class='itemNormal' windex='"+aIndex+"'>"+"<span class='fl'>"+tmp+"</span>"+"<span class='fr'>"+lastComments[aIndex]+"</span>"+"</div>\n";});$("#suglist").append(tHtml).show();}else{if(lastResult[0]=="暂无常用词提示"){$("#suglist_panel").hide();return false;}
$.each(lastResult,function(aIndex){$("#suglist").append("<div class='itemNormal' index='"+aIndex+"'>"+"<span class='textlft'>"+lastResult[aIndex].replace(reg,"<b>$1</b>")+"</span>"+"</div>").show();});}
$(".itemNormal").hover(function(){var tsugSelectIndex=Number($(this).removeClass("itemNormal").addClass("itemOver").attr("windex"));if(tsugSelectIndex!=sugSelectIndex){$("#suglist > div").eq(sugSelectIndex).removeClass("itemOver").addClass("itemNormal");sugSelectIndex=tsugSelectIndex;}},function(){$(this).removeClass("itemOver").addClass("itemNormal");}).click(function(){if($(this).find("span:first").text()!="暂无常用词提示")
{SetWinput($(this).find("span:first").text());onSubmit();}});$("#suglist_panel").css("display","block");}catch(e){hasResult=false;}}else{hasResult=false;$("#suglist").html("");$("#suglist").css("height","auto");$("#suglist_panel").css("display","none");}}
function JpSugLoaded(data){if(data.length>0){try{data=eval(data);lastResult=data[1];var sugword=data[0];if(data.length==3){lastComments=eval(data)[2];}else{lastComments=[];}
hasResult=true;if(lastResult.length>10){$("#suglist").css("height","250px");}else{$("#suglist").css("height","auto");}
sugSelectIndex=-1;var reg=new RegExp("("+OldWord+")","igm");if(sugword==OldWord){if(lastComments.length!=0){$("#suglist").html("");var tHtml="";$.each(lastResult,function(aIndex){var dbWord=lastResult[aIndex];tmpWord=dbWord.substr(0,OldWord.length);var tmp="<b>"+dbWord.substr(0,OldWord.length)+"</b>"+dbWord.substr(OldWord.length);tHtml+="<div class='itemNormal' windex='"+aIndex+"'>"+"<span class='fl'>"+tmp+"</span>"+"<span class='fr'>"+lastComments[aIndex]+"</span>"+"</div>\n";});$("#suglist").append(tHtml).show();}else{if(lastResult[0]=="暂无常用词提示"){$("#suglist_panel").hide();return false;}
$.each(lastResult,function(aIndex){$("#suglist").append("<div class='itemNormal' index='"+aIndex+"'>"+"<span class='textlft'>"+lastResult[aIndex].replace(reg,"<b>$1</b>")+"</span>"+"</div>").show();});}}else{if(tmpWord!=OldWord)
{$("#suglist").html("");}}
$(".itemNormal").hover(function(){var tsugSelectIndex=Number($(this).removeClass("itemNormal").addClass("itemOver").attr("windex"));if(tsugSelectIndex!=sugSelectIndex){$("#suglist > div").eq(sugSelectIndex).removeClass("itemOver").addClass("itemNormal");sugSelectIndex=tsugSelectIndex;}},function(){$(this).removeClass("itemOver").addClass("itemNormal");}).click(function(){if($(this).find("span:first").text()!="暂无常用词提示"){SetWinput($(this).find("span:first").text());onSubmit();}});$("#suglist_panel").css("display","block");}catch(e){hasResult=false;}}else{hasResult=false;$("#suglist").html("");$("#suglist").css("height","auto");$("#suglist_panel").css("display","none");}}
$(function(){initSearchWord();$("#w").keydown(function(aevent){aevent=aevent||window.event;if(aevent.keyCode==40){ShiftSelect(sugSelectIndex+1);}else if(aevent.keyCode==38){ShiftSelect(sugSelectIndex-1);}else if(aevent.keyCode==13){$("#suglist_panel").css("display","none");}});$(document).click(function(){$("#suglist_panel").css("display","none");});InputTimer=setInterval("DetectInput()",150);});function initSearchWord()
{var showTip="";subEnabled=(HjDict.Cookie.Get("hjd_sugEnabled")=="on"?true:false);try{if(subEnabled){$("#spell_tips").attr("class","spell_tips");$("#suglist_form").show();showTip='<a href="###" onclick="ShiftSugEnabled(false,this)">关闭提示功能</a>';}else{$("#spell_tips").attr("class","no_spell_tips");showTip='<a href="###" onclick="ShiftSugEnabled(true,this)">开启提示功能</a>';}}catch(e){}
var tForm=$("#suglist_form");if(tForm!=null){tForm.html('<div id="suglist_panel" style="display:none;">'+'<div id="suglist" class="wordlist" style="display:none">'+'</div>'+'<div id="btn_tips">'+showTip+'</div>'+'</div>');OldWord=JustInputForTimer=$("#w").val();}}
(function(){var win=window;if(win['HJ_Dict_Input']===undefined)win['HJ_Dict_Input']={};var HJ_Dict_Input=win['HJ_Dict_Input'];var srf_colums=0;var srf_currentLang='jp_pin';var ht_fr=new Array(["à","à"],["â","â"],["ç","ç"],["é","é"],["è","è"],["ê","ê"],["ë","ë"],["î","î"],["ï","ï"],["ô","ô"],["œ","œ"],["ù","ù"],["û","û"],["À","À"],["Â","Â"],["Ç","Ç"],["É","É"],["È","È"],["Ê","Ê"],["Ë","Ë"],["Î","Î"],["Ï","Ï"],["Ô","Ô"],["Œ","Œ"],["Ù","Ù"],["Û","Û"]);var ht_jp_pin=new Array(["a","あ"],["ka","か"],["sa","さ"],["ta","た"],["na","な"],["ha","は"],["ma","ま"],["ya","や"],["ra","ら"],["wa","わ"],["ga","が"],["za","ざ"],["da","だ"],["ba","ば"],["pa","ぱ"],["a","ぁ"],["ya","ゃ"],["&nbsp;",""],["「","「"],["i","い"],["ki","き"],["shi","し"],["chi","ち"],["ni","に"],["hi","ひ"],["mi","み"],["&nbsp;",""],["ri","り"],["&nbsp;",""],["gi","ぎ"],["ji","じ"],["di","ぢ"],["bi","び"],["pi","ぴ"],["i","ぃ"],["&nbsp;",""],["&nbsp;",""],["」","」"],["u","う"],["ku","く"],["su","す"],["tsu","つ"],["nu","ぬ"],["fu","ふ"],["mu","む"],["yu","ゆ"],["ru","る"],["&nbsp;",""],["gu","ぐ"],["zu","ず"],["du","づ"],["bu","ぶ"],["pu","ぷ"],["u","ぅ"],["yu","ゅ"],["tsu","っ"],["ー","ー"],["e","え"],["ke","け"],["se","せ"],["te","て"],["ne","ね"],["he","へ"],["me","め"],["&nbsp;",""],["re","れ"],["&nbsp;",""],["ge","げ"],["ze","ぜ"],["de","で"],["be","べ"],["pe","ぺ"],["e","ぇ"],["&nbsp;",""],["&nbsp;",""],["・","・"],["o","お"],["ko","こ"],["so","そ"],["to","と"],["no","の"],["ho","ほ"],["mo","も"],["yo","よ"],["ro","ろ"],["wo","を"],["go","ご"],["zo","ぞ"],["do","ど"],["bo","ぼ"],["po","ぽ"],["o","ぉ"],["yo","ょ"],["n","ん"],["？","？"]);var ht_jp_pian=new Array(["a","ア"],["ka","カ"],["sa","サ"],["ta","タ"],["na","ナ"],["ha","ハ"],["ma","マ"],["ya","ヤ"],["ra","ラ"],["wa","ワ"],["ga","ガ"],["za","ザ"],["da","ダ"],["ba","バ"],["pa","パ"],["a","ァ"],["ya","ャ"],["&nbsp;",""],["「","「"],["i","イ"],["ki","キ"],["shi","シ"],["chi","チ"],["ni","ニ"],["hi","ヒ"],["mi","ミ"],["&nbsp;",""],["ri","リ"],["&nbsp;",""],["gi","ギ"],["ji","ジ"],["&nbsp;",""],["bi","ビ"],["pi","ピ"],["i","ィ"],["&nbsp;",""],["&nbsp;",""],["」","」"],["u","ウ"],["ku","ク"],["su","ス"],["tsu","ツ"],["nu","ヌ"],["fu","フ"],["mu","ム"],["yu","ユ"],["ru","ル"],["&nbsp;",""],["gu","グ"],["zu","ズ"],["&nbsp;",""],["bu","ブ"],["pu","プ"],["u","ゥ"],["yu","ュ"],["tsu","ッ"],["ー","ー"],["e","エ"],["ke","ケ"],["se","セ"],["te","テ"],["ne","ネ"],["he","ヘ"],["me","メ"],["&nbsp;",""],["re","レ"],["&nbsp;",""],["ge","ゲ"],["ze","ゼ"],["de","デ"],["be","ベ"],["pe","ぺ"],["e","ェ"],["&nbsp;",""],["&nbsp;",""],["・","・"],["o","オ"],["ko","コ"],["so","ソ"],["to","ト"],["no","ノ"],["ho","ホ"],["mo","モ"],["yo","ヨ"],["ro","ロ"],["wo","ヲ"],["go","ゴ"],["zo","ゾ"],["do","ド"],["bo","ボ"],["po","ポ"],["o","ォ"],["yo","ョ"],["n","ン"],["？","？"]);function BindLang(obj,pos){if(arguments.length==1){pos='down';}
ShowTips(obj,pos);$(obj).focus(function(){setCaret(this);});$(obj).select(function(){setCaret(this);});$(obj).click(function(){setCaret(this);});$(obj).keyup(function(){setCaret(this);});}
HJ_Dict_Input.BindLang=BindLang;function ShowTips(obj,pos){if($(obj).parent().attr("class")!="wrap"){$(obj).wrap("<div class='wrap' title='"+pos+"'></div>");}
if($(obj).parent().find(".srf_link_showTip").length==0){$(obj).parent().prepend("<div class='srf_link_showTip' title='打开输入法' ></div>");$(obj).parent().find(".srf_link_showTip").toggle(function(){ShowButtons(obj);},function(){HideButtons(obj);});}}
function HideTips(obj){if($(obj).parent().find(".srf_link_showTip").length>0&&$(obj).parent().find(".srf_pnl_buttons").length==0)
$(obj).parent().find(".srf_link_showTip").remove();}
function ShowButtons(obj){var srf_position=$(obj).parent().attr("title");var txtWidth=$(obj).width();$(obj).parent().find(".srf_link_showTip").css("background","url(/app/images/bckground_all.gif) no-repeat 0 -177px").attr("title","关闭输入法");if($(obj).parent().find(".srf_pnl_buttons").length==0){$(obj).parent().append("<div class='srf_pnl_buttons' style='display:none'></div>");GetButtons(srf_currentLang,$(obj).parent().find(".srf_pnl_buttons"));if(srf_position=='down'){$(obj).parent().find(".srf_pnl_buttons").css("top",$(obj).height()+10);$(obj).parent().find(".srf_pnl_buttons").find("table").css("float","right");$(obj).parent().find(".srf_pnl_buttons").css("left",0);if(txtWidth>275){$(obj).parent().find(".srf_pnl_buttons").css("width",txtWidth*1+6);$(obj).parent().find(".wrap_head").css("width",$(obj).parent().find(".srf_pnl_buttons").find("table").width());}}
if(srf_position=='right'){$(obj).parent().find(".srf_pnl_buttons").css("top",20);$(obj).parent().find(".srf_pnl_buttons").find("table").css("float","left");$(obj).parent().find(".srf_pnl_buttons").css("left",$(obj).width()+10);}
$(obj).parent().find(".srf_pnl_buttons").show();}}
function HideButtons(obj){$(obj).parent().find(".srf_link_showTip").css("background","url(/app/images/bckground_all.gif) no-repeat 0 -160px").attr("title","打开输入法");$(obj).parent().find(".srf_pnl_buttons").remove();}
function GetButtons(lang,obj){var list=null;if(lang=='jp_pin'){srf_colums=19;list=ht_jp_pin;srf_currentLang='jp_pin';}
if(lang=='jp_pian'){srf_colums=19;list=ht_jp_pian;srf_currentLang='jp_pian';}
if(lang=='fr'){srf_colums=13;list=ht_fr;srf_currentLang='fr';}
$(obj).html("");var html="<table class='srf_tbl_lang'><tr><td class='srf_tbl_head_td' style='padding:0px' colspan='"+srf_colums+"'><div class='srf_tbl_head'><div class='srf_close' title='点此关闭'></div><div class='srf_pnl_langs'>"+GetLangRadios()+"</div></div></td></tr><tr>"
for(var i=0;i<list.length;i++){var ht_lb=list[i];html+="<td style='background-color:#F4F5FB; color:#3772D3'>";if(ht_lb[1]!=""){html+="<a href='###' class='td_word' title='"+ht_lb[0]+"' style='font-size:14px; font-family:Osaka,\"MS PGothic\",\"ＭＳ Ｐゴシック\",Arial,\"sans-serif\"; display:block; width:100%; height:100%;' >"+ht_lb[1]+"</a>"}
html+="</td>";if((i+1)%srf_colums==0){html+="</tr><tr>";}}
html+="</tr><div style='clear:both'></div></table>";$(obj).html(html);$(obj).find("a").click(function(){doadd(this);});if(lang=='jp_pin'){$(obj).find(".srf_pnl_langs").after("<div class='srf_jpName'>平假名 | <a class='srf_Topian' href='###'>片假名</a></div>");$(obj).find(".srf_Topian").click(function(){GetButtons('jp_pian',obj);});$(obj).find(".srf_lst_lang").val('jp_pin');ChangeSpecalColor(9,obj);}
if(lang=='jp_pian'){$(obj).find(".srf_pnl_langs").after("<div class='srf_jpName'><a class='srf_Topin' href='###'>平假名</a> | 片假名");$(obj).find(".srf_Topin").click(function(){GetButtons('jp_pin',obj);});$(obj).find(".srf_lst_lang").val('jp_pin');ChangeSpecalColor(9,obj);}
else
$(obj).find(".srf_lst_lang").val(lang);$(obj).find(".srf_tbl_lang").find("td").mouseover(function(){if($(this).attr("class")!="srf_tbl_head_td"){if($(this).find("a").length>0){var bgcolor=$(this).css("background-color");var fontcolor=$(this).css("color");$(this).css("background-color",fontcolor).css("color",bgcolor);$(this).find("a").css("color",bgcolor);}}});$(obj).find(".srf_tbl_lang").find("td").mouseout(function(){if($(this).attr("class")!="srf_tbl_head_td"&&$(this).find("a").length>0){var bgcolor=$(this).css("background-color");var fontcolor=$(this).css("color");$(this).css("background-color",fontcolor).css("color",bgcolor);$(this).find("a").css("color",bgcolor);}});$(obj).find(".srf_lst_lang").change(function(){GetButtons($(this).val(),obj);});$(obj).find(".srf_close").click(function(){$(obj).parent().find(".srf_link_showTip").click();});}
function ChangeSpecalColor(columnIndex,obj){var td_index=0;$(obj).find(".srf_tbl_lang").find("tr").each(function(){$(this).find("td").each(function(){if(td_index>columnIndex){$(this).css("color","#527836");$(this).find("a").css("color","#527836");}
td_index++;});td_index=0;});}
function GetLangRadios(){return"<span style='color:#4B81D8;font-weight:700;padding-left:3px'>日本語</span>";}
function doadd(obj){var txt=$(obj).parent().parent().parent().parent().parent().parent().find(".srf_link_showTip").next();var id=$(txt).attr("id");insertAtCaret($(txt)[0],$(obj).html());}
function setCaret(textObj){if(textObj.createTextRange){textObj.caretPos=document.selection.createRange().duplicate();}}
function insertAtCaret(textObj,textFeildValue){if(document.all){if(textObj.createTextRange&&textObj.caretPos){var caretPos=textObj.caretPos;caretPos.text=caretPos.text.charAt(caretPos.text.length-1)=='   '?textFeildValue+'   ':textFeildValue;}
else{textObj.value=textFeildValue;}}
else{if(textObj.setSelectionRange){var rangeStart=textObj.selectionStart;var rangeEnd=textObj.selectionEnd;var tempStr1=textObj.value.substring(0,rangeStart);var tempStr2=textObj.value.substring(rangeEnd);textObj.value=tempStr1+textFeildValue+tempStr2;setCaretPosition(textObj,rangeEnd+1);}
else{alert("This   version   of   Mozilla   based   browser   does   not   support   setSelectionRange");}}}
function setCaretPosition(ctrl,pos){if(ctrl.setSelectionRange){ctrl.focus();ctrl.setSelectionRange(pos,pos);}
else if(ctrl.createTextRange){var range=ctrl.createTextRange();range.collapse(true);range.moveEnd('character',pos);range.moveStart('character',pos);range.select();}}})();
function Submit(type){if(!type){type="jc";}
var word=$("#w").val();word=word.replace(" ","");var Searchby_letter="";var reg=/([a-zA-Z\.0-9-]{1,})/igm
if(reg.test(unescape(word))){Searchby_letter="&letter=1";}else{reg=/([\u3042-\u30f6]{1,})/igm
if(reg.test(word)){type="jc";}}
if(word.length==0||word==""){alert("请输入查询内容！");return false;}else{try{window.location="/jp/"+type+"/"+encodeURIComponent($("#w").val().replace(" ","+"))+Searchby_letter;}catch(e){window.location="/jp/"+type+"/"+$("#w").val().replace(" ","+")+Searchby_letter;}
return false;}}
var _Submited=false;function OnWordChange(){subEnabled=(HjDict.Cookie.Get("hjd_sugEnabled")=="on"?true:false);if(!subEnabled){return false;}
var tword=$("#w").val();if(OldWord!=tword&&tword.length>0){OldWord=tword;$.get("/services/sug/jp.ashx",{q:OldWord,com:hjd_hasComment},JpSugLoaded);}
else if(tword.length==0){if(!selectOpen){OldWord="";$("#suglist").html("");$("#suglist").css("height","auto");$("#suglist_panel").css("display","none");}}}
function onSubmit(){if($("#w").val().length==0||$("#w").val()=="请输入要查询的单词"){alert("请输入要查询的单词");$("#w").focus();}else{if(!_Submited){_Submited=true;var word=$("#w").val();word=word.replace(/^( )*/igm,"").replace(/( )*HJ$/igm,"");window.location="/jp/jc/"+word.replace(" ","+");}}
return false;}
function SubmitSent(){var sent=$("#w").val();sent=sent.replace(" ","");if(sent.length==0||sent==""){alert("请输入查询内容！");return false;}else{window.location="/app/jp/sent/"+encodeURI($("#w").val());window.event.returnValue=false;return false;}}
$(function(){HJ_Dict_Input.BindLang($("#w"),"jp_pin");});var shiftLang="cj";$(function(){$("#translate").live("click",function(){if(shiftLang=="cj"){shiftLang="jc";$(this).html("日→中");$(this).attr("title","日中翻译");$(".searchWord").show();$(".searchSent").hide();return;}
if(shiftLang=="jc"){shiftLang="cj";$(this).html("中→日");$(this).attr("title","中日翻译");$(".searchSent").hide();$(".searchWord").show();return;}});});function newFavSentence(word,sid,sentence,trans,sentType){if(sentType==undefined)
sentType=1;return AjaxMethod("/app/top","NewFavSentence","{lang:'jp',word:'"+word+"',sid:'"+sid+"',sentence:'"+sentence+"',trans:'"+trans+"',sentType:"+sentType+"}");}
function newSaveSentences(obj,sid,sentence,trans){try{var sentType=arguments[4]?arguments[4]:1;var result=AjaxMethod("/jp","SentenceInfo","{SID:'"+sid+"',sentType:"+sentType+"}");if(result=="unlogin"){window.hjquicklogin.doLogin();}
else{var results=newFavSentence(word_title,sid,sentence,trans,sentType);if(results==true||results=="true"||(results&&results.value)){$(obj).before("<span class='green'>已收藏</span>");$(obj).after("<a target='_blank' href='/app/mysent/1_2/' class='noline ml10' title='访问例句本'>访问例句本</a>");$(obj).remove();}else{$(obj).html("收藏失败。。");}}}catch(e){}}
function loadSiteSearch(lang,keyword,containerID,option){option=option||{};var default_option={showPager:true,showContent:true,loadMore:false,itemCount:2,onNotFound:function(){}};option=$.extend({},default_option,option);if($("#"+containerID).size()==0){return;}
var site={en:"www.hjenglish.com/new",jp:"jp.hjenglish.com/new",all:"hjenglish.com",fr:"fr.hujiang.com/new",kr:"kr.hujiang.com/new",cn:"cn.hujiang.com"}[lang];var template="";if(option.showContent){template='<div class="site_search_result">'+'<div class="result_title"><a target="_blank" href="${url}">${title}</a></div>'+'<div class="result_content">${content}</div>'+'</div>';}else{template='<div>'+'<a target="_blank" class="result_title_small" href="${url}" >${title}</a><br/>'+'</div>';}
var searchComplete=function(){$("#"+containerID).html("");if(this.results&&this.results.length>0){for(var i=0;i<this.results.length;i++){if(i==option.itemCount){break;}
var result=this.results[i];var html=template;var title=result.titleNoFormatting;title=title.replace(/_.*/,"");var content=result.content;content=content.replace(/<b>\.\.\.<\/b>/g,"...");content=content.replace(/\.\.\.$/,"");content+="  ...";html=html.replace("${title}",title);html=html.replace("${content}",content);html=html.replace("${url}",result.unescapedUrl.replace("/new/print/","/new/p"));var urlDisplay=result.unescapedUrl;if(urlDisplay.length>50){urlDisplay=urlDisplay.substr(0,50)+"  <b>...</b>";}
$("#"+containerID).append(html);}
if(option.showPager){document.getElementById(containerID).search=this;var cursor=this.cursor;var pageLength=cursor.pages.length;var curPage=cursor.currentPageIndex;var $pageContainer=$("<div class='page_container'></div>");for(var i=0;i<pageLength;i++){var page=cursor.pages[i];if(curPage==i){$pageContainer.append($("<span></span>").text(page.label));}else{var link=$("<a href='###'></a>").text(page.label);link.attr("href",'javascript:document.getElementById("'+containerID+'").search.gotoPage('+i+');');$pageContainer.append(link);}}
if(pageLength>1){if(curPage+1<pageLength){var link=$("<a href='###'></a>").text("下一页 >");link.attr("href",'javascript:document.getElementById("'+containerID+'").search.gotoPage('+(curPage+1)+');');$pageContainer.append(link);}
if(curPage>0){var link=$("<a href='###'></a>").text("< 上一页");link.attr("href",'javascript:document.getElementById("'+containerID+'").search.gotoPage('+(curPage-1)+');');$pageContainer.prepend(link);}}
$("#"+containerID).append($pageContainer);}
$(".site_article").show();$("#PanelSiteSearch").show();}else{$("#"+containerID).html("<div class='result_empty'>抱歉，站内没有相关内容!<div>");option.onNotFound();}}
var search=new google.search.WebSearch();if(option.loadMore){search.setResultSetSize(google.search.Search.LARGE_RESULTSET);}else{search.setResultSetSize(google.search.Search.SMALL_RESULTSET);}
search.setSearchCompleteCallback(search,searchComplete);search.execute("site:"+site+" -dict.hjenglish.com -dict.yeshj.com "+keyword);}
function HJ$(aControlID){return document.getElementById(aControlID);}
function ShiftVisible(aObjName){var targetElement=$(aObjName);if(targetElement.style.display=="none"||targetElement.style.display==""){targetElement.style.display="block";}else{targetElement.style.display="none";}
return false;}
function ShiftVisible_jpcom(aObjName,a_linkObj,a_Bool){var targetElement=HJ$(aObjName);if(typeof(a_Bool)=="undefined"||a_Bool==null){if(targetElement.style.display=="none"||targetElement.style.display==""){targetElement.style.display="block";a_linkObj.innerHTML="<b>[ - ]</b>";}else{targetElement.style.display="none";a_linkObj.innerHTML="<b>[ + ]</b>";}}else{if(a_Bool){targetElement.style.display="block";a_linkObj.innerHTML="<b>[ - ]</b>";}else{targetElement.style.display="none";a_linkObj.innerHTML="<b>[ + ]</b>";}}
return false;}
function ShiftExplanPanels(aObjCounts,aLinkObj){if(expen_click=="-"){expen_click="+";aLinkObj.innerHTML="<b>[ + ]</b>";for(var i=0;i<aObjCounts;i++){ShiftVisible_jpcom("com_panel_"+i,HJ$("click2expend_"+i),false);}}else{expen_click="-";aLinkObj.innerHTML="<b>[ - ]</b>";for(var i=0;i<aObjCounts;i++){ShiftVisible_jpcom("com_panel_"+i,HJ$("click2expend_"+i),true);}}}
function textOnOff(aObj){ShiftVisible(aObj+"_more");ShiftVisible(aObj+"_less");return false;}
function ShiftCommentArea(aObj){ShiftVisible(aObj+"_content");ShiftVisible(aObj+"_hint");return false;}
var Clipboard=0;function CopyUrl(){copyit(window.location.toString());return false;}
function Copycomment(){var reg=/(<BR>)/igm;copyit(_word_title+"\r\n"+HJ$("panel_comment").innerHTML.replace(reg,"\r\n")+"\r\n（沪江在线词典：dict.hjenglish.com）");HJ$("link_Copycomment").html="<font color=red>复制成功</font>"
return false;}
function GetClipboard(){return Clipboard;}
function copyit(textit){Clipboard=textit;if(window.clipboardData){window.clipboardData.setData("Text",textit);}else{var flashcopier='flashcopier';if(!$(flashcopier)){var divholder=document.createElement('div');divholder.id=flashcopier;document.body.appendChild(divholder);}
$(flashcopier).innerHTML='';var divinfo='<embed src="/common/_clipboard.swf" width="0" height="0" type="application/x-shockwave-flash" id="flashforcopy" name="flashforcopy"></embed>';$(flashcopier).innerHTML=divinfo;}
alert("地址复制成功！");}
function onInit(){_pageloaded=true;HJ$("w").focus();try{var rng=HJ$("w").createTextRange();rng.select();}catch(e){HJ$("w").select();}}
function SelectInput(){document.getElementById("w").focus();document.getElementById("w").select();}
function QueryWord(aword){if(window._dictShow){_dictShow(aword);}}
function ShiftSugJpEnabled(aBool){subJpEnabled=aBool;_wListInited=aBool;setcookie("hjd_sugJpEnabled",aBool?"on":"off",9999999,"/","dict.hjenglish.com");}
function onChange(aevent){return;if(navigator.userAgent.indexOf('Opera')>-1&&aevent.keyCode==13){location.href="/app/jp/jc/"+word;}
if(!aevent){aevent=window.event;}
if(aevent.keyCode!=40&&aevent.keyCode!=38){if(_wListInited){var word=HJ$("w").value;if(word.length<0){document.getElementById("jpSuglist").style.display="none";return;}
try{var rex="あアいイうウえエおオ"+"かカきキくクけケこコ"+"さサしシすスせセそソ"+"たタちチつツてテとト"+"なナにニぬヌねネのノ"+"はハひヒふフへヘほホ"+"まマみミむムめメもモ"+"やヤゆユよヨ"+"らラりリるルれレろロ"+"わワをヲ"+"んン"+"がガぎギぐグげゲごゴ"+"ざザじジずズぜゼぞゾ"+"だダぢヂづヅでデどド"+"ばバびビぶブべベぼボ"+"ぱパぴピぷプぺペぽポ"+"きゃキャきゅキュきょキョ"+"しゃシャしゅシュしょショ"+"ちゃチャちゅチュちょチョ"+"にゃニャにゅニュにょニョ"+"ひゃヒャひゅヒュひょヒョ"+"みゃミャみゅミュみょミョ"+"りゃリャりゅリュりょリョ"+"ぎゃギャぎゅギュぎょギョ"+"じゃジャじゅジュじょジョ"+"びゃビャびゅビュびょビョ"+"ぴゃピャぴゅピュぴょピョ";var kana=word.substr(word.length-1,1);if(rex.indexOf(kana)>-1){$.get("/services/jp_sug_search.ashx",{jpw:word},function(data){ReturnList(data);});}else{document.getElementById("jpSuglist").style.display="none";}}catch(e){}}}}
function OnKeyDown(aevent){}
function OnKeyDownSent(aevent){if(!aevent){aevent=window.event;}
if(aevent.keyCode==13){SubmitSent();}}
var _initdisable=false;function ShiftDictable2(aBool){try{if(_pageloaded){ShiftDictable(aBool);}}
catch(e){}}
function HistoryInited(){getwHistoryObj().AppendHistory(_wordhistory,ReferPage,hasResult);return;}
function ShowHistory(aWList){var Html="";if(aWList!="null"&&aWList!=null){aWList=aWList.split("|");var aCount=Math.min(12,aWList.length);for(var i=0;i<aCount;i++){var aItemInfo=aWList[i].split("[=]");if(aItemInfo.length==1){getwHistoryObj().AppendHistory('--!--');return;}
var link=ParseHistoryItem(aItemInfo[0]);if(link[1]==""){}else{Html+="<li><a href=\"/jp/w/"+encodeURI(link[0])+"&type="+link[1]+"\">"+link[0]+"</a>";}}
Html="<ol>"+Html+"</ol>";}else{Html="<ul><li>暂无记录</li></ul>";document.getElementById("panel_clearhistory").style.display="none";}
document.getElementById("panel_history").innerHTML=Html;return;}
function chw_callback(result){if(result.error==null){if(result.value=="no"){$('suggest2mydict_panel').style.display="block";}}}
function Suggest2MyDict(anewword){}
function ParseHistoryItem(aItemString){if(aItemString.indexOf("{j}")!=-1){return[aItemString.replace("{j}",""),"jc"];}else if(aItemString.indexOf("{c}")!=-1){return[aItemString.replace("{c}",""),"cj"];}else{return[aItemString,""];}}
function getwHistoryObj(){if(navigator.appName.indexOf("Microsoft")!=-1&&navigator.userAgent.indexOf("MSIE 9.0")<0&&navigator.userAgent.indexOf("MSIE 10.0")<0){return window.ahistory;}else{return window.document.ahistory;}}
function shiftsearchby_letter_label(){}
var _wListInited=true;var ItemSelected=-1;var LastCompleteWord="";function ReturnList(aList){var word=document.getElementById("w").value;var ItemHtml="";if(aList!=""&&aList!=null){if(aList.indexOf("|")>-1){aList=aList.split("|");var showAmount=10;if(aList.length<10){showAmount=aList.length;}
for(var i=0;i<showAmount;i++){var jpWord=aList[i].split("@@")[0].replace(word,"<span style='font-weight:bold;'>"+word+"</span>");var jpComment=aList[i].split("@@")[1];ItemHtml+="<div id='item_"+i+"' class='itemNormal' onclick='wordSelect(this);' onmouseover='MouseOver(this);' onmouseout='MouseOut(this);'><span style='float:left;'>"+jpWord+" </span><span style='float:right;'>"+jpComment+"</span></div>";}}else{ItemHtml=aList;}
ItemSelected=-1;}else{return;}}
function getwListObj(){if(navigator.appName.indexOf("Microsoft")!=-1){return window.aFlash;}else{return window.document.aFlash;}}
function MouseOver(aObj){aObj.className="itemOver";}
function MouseOut(aObj){aObj.className="itemNormal";}
function wordSelect(aObj){if(document.all){document.getElementById("w").value=aObj.innerText.split(" ")[0];}else{document.getElementById("w").value=aObj.textContent.split(" ")[0];}
ItemSelected=Number(document.getElementById("w").getAttribute("id").split("_")[1]);}
function ShiftSelect(step){var aNObj=document.getElementById("item_"+(ItemSelected+step));if(aNObj!=null){if(ItemSelected!=-1){document.getElementById("item_"+ItemSelected).className="itemNormal";}
ItemSelected=ItemSelected+step;aNObj.className="itemOver";if(document.all){document.getElementById("w").value=aNObj.innerText.split(" ")[0];}else{document.getElementById("w").value=aNObj.textContent.split(" ")[0];}}}
function wlistInited(){_wListInited=true;}
function MouseDownOnBody(aevent){if(!aevent){aevent=window.event;}
var srcElement;if(document.all){srcElement=aevent.srcElement;}else{srcElement=aevent.target;}}
function amw_callback(result){if(result.error!=null){alert(result.error);return;}
var retValue=result.value[0];var aTurnID=result.value[1];var html="";if(retValue=="login"){html='<a href="###" onclick="Do_AddMyWord('+aTurnID+');return false;"><img src="/images/btn_myword_add.gif" alt="将这个单词添加到我的生词本"/></a></a>';document.getElementById("amw_panel_"+aTurnID).innerHTML=html;if(document.getElementById("amw_panel_lnk_"+aTurnID)){document.getElementById("amw_panel_lnk_"+aTurnID).innerHTML=html;}
window.hjquicklogin.doLogin();return false;}
if(retValue=="yes"){html='<a href="http://'+_HjDict_MyDictUrl+'/scb/" title="查看我的生词本">添加成功，访问生词本</a>';}else if(retValue=="no"){html='<a href="http://'+_HjDict_MyDictUrl+'/scb/" title="查看我的生词本">已添加，访问生词本</a>';}else if(retValue=="error"){html='添加失败';}
document.getElementById("amw_panel_"+aTurnID).innerHTML=html;if(document.getElementById("amw_panel_lnk_"+aTurnID)){document.getElementById("amw_panel_lnk_"+aTurnID).innerHTML=html;}}
function addMydictWord(aID,langsType,userID,wordid,fromlang,tolang){var expcom="";var word=$("#jpword_"+aID).html();var kana=$("#kana_"+aID).text();var wordComment=$("#headword_jp_"+aID).find(".simple_content").html();if(wordComment==""||wordComment==undefined){expcom=$("#headword_jp_"+aID).find(".jp_definition_com").html();expcom=expcom.replace(/\n\s+/,'').replace(/<[^>]+/g,"").replace(/>+/g,"");var typestr=$("#headword_jp_"+aID).find("div .big_type").html()==null?"":$("#headword_jp_"+aID).find("div .big_type").html();if(expcom==""||expcom==null||expcom==undefined){expcom=$(".word_comment").html();}
wordComment=typestr+expcom;}
if(wordComment==""||wordComment==undefined){var com=$(".jp_explain").html();if(com==""||com==null||com==undefined)
{com=$(".word_comment").html();}
wordComment=$("div .big_type").html()+com;}
wordComment=wordComment.replace(/<br\/>/igm,"\n");wordComment=wordComment.replace(/<br>/igm,"\n");var regEx=/<[^>]*>/g;wordComment=wordComment.replace(regEx,"");if(kana!=""&&kana!=null){wordComment=kana+"\n"+wordComment;}
wordComment=wordComment.split("日英：")[0];wordComment=encodeURI(wordComment);$.ajax({type:"POST",dataType:"json",url:"/ajax/jp/AddMyWord",contentType:"application/json;charset=utf-8",data:$.toJSON({word:word,comment:wordComment,langs:11,wordid:wordid,fromlang:fromlang,tolang:tolang,source:"",extkey:""}),success:function(data){if(data.d==1||data.d==0){$("#amw_panel_"+aID).html("<a href='/scb/' title='查看我的生词本' style='width:16px; height:16px;'><img src='/images/btn_myword_del.gif' alt='查看我的生词本' width='16px' height='16px' align='absmiddle'></a>");}
else{if(data.d==-1){$("#amw_panel_"+aID).html("添加失败~");}
else{window.hjquicklogin.aID=aID;window.hjquicklogin.langsType=langsType;window.hjquicklogin.userID=userID;window.hjquicklogin.doLogin({callback:addMydictWord});return false;}}
if(window.hjquicklogin.flag&&window.hjquicklogin.flag=="logincallback"){window.hjquicklogin.flag="";window.location.reload();}},timeout:1000*15});}
function Do_AddMyWord(aID){var comment=HJ$(".simple_content").value;comment=comment.replace(/<br><br>/igm,"\n");comment=comment.replace(/<br\/>/igm,"\n");comment=comment.replace(/<br>/igm,"\n");var regEx=/<[^>]*>/g;comment=comment.replace(regEx,"");PageClassNew.AddMyWord(HJ$("amw_word_"+aID).value,comment,_ReferPage,_searchtype,aID,amw_callback);}
function AddMyWord(aID){document.getElementById("amw_panel_"+aID).innerHTML='<img align="absmiddle" src="/images/loading.gif" />';if(document.getElementById("amw_panel_lnk_"+aID)){document.getElementById("amw_panel_lnk_"+aID).innerHTML='<img align="absmiddle" src="/images/loading.gif" />';}
setTimeout("Do_AddMyWord("+aID+");",500);}
function showSpellTip(){if($("#spell_tips").attr("class")=="no_spell_tips"){$("#spell_tips").attr("class","spell_tips");subJpEnabled=true;}else{$("#spell_tips").attr("class","no_spell_tips");subJpEnabled=false;}
ShiftSugJpEnabled(subJpEnabled);}